### ISSUE TITLE
PalindromosAleatorios.md

### ISSUE THREAD

**Issue by kamuridesu** [LeoScripts/testes-de-empresas#1]
Qual seu email?

**Comment by LeoScripts** [comment]
***@***.***

Em sex., 25 de fev. de 2022 às 09:23, Kamuri Amorim <
***@***.***> escreveu:

**Comment by LeoScripts** [comment]
leandroguitarjesus89@gmail.com

**Comment by LeoScripts** [comment]
> Qual seu email?
leandroguitarjesus89@gmail.com

**Comment by kamuridesu** [comment]
.
